version: "3.9"
networks:
  hermes-producer:
    driver: bridge
services:
#  zookeeper:
#    image: zookeeper:3.8.0
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    restart: "no"

  kafka:
    image: bitnami/kafka:3.2.1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: "no"
    networks:
      - hermes-producer


  mongodb:
    image: mongo:6.0.1
    restart: "no"
    ports:
      - ${HERMES_MONGODB_PORT:-27018}:27017
    networks:
      - hermes-producer




