version: "3.9"

services:
  # Do not directly set the host of each node to 127.0.0.1.
  # When you change the kafka_node_1, kafka_node_2, and kafka_node_3 to 127.0.0.1 directly in your YAML file,
  # you are telling Kafka to use the loopback address as the advertised listener.
  # However, other nodes in your Kafka cluster will not be able to connect to Kafka using the loopback address because
  # it is a local address and not accessible from other machines.
  kafka_node_1:
    restart: "no"
    image: bitnami/kafka:latest
    ports:
      - '9092-9093:9092-9093'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=7UYiXsIxQXaqrYVjztiofw
      - KAKFA_HEAP_OPTS=-Xmx128M -Xms16M
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Listen requests from these paths (Default empty value is localhost)
      # If your kafka node and client are not running on the same machine, please set to listen the client address (0.0.0.0)
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Tell clients which address you can communicate with me.
      # If your kafka nodes are not running on the same network, please use the external real IP address
      # ADVERTISED_LISTENERS will be sent back to clients to resolve. So if you are using hostname instead of
      # IP address, pls make sure that the client has the hostnames mapping to IP addresses.
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  mongodb:
    image: mongo:6.0.1
    restart: "no"
    ports:
      - ${HERMES_MONGODB_PORT:-27018}:27017
    # config user auth for mongo in the future
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${HERMES_MONGODB_ROOT_USER_NAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${HERMES_MONGODB_ROOT_USER_PASSWORD}
#      MONGO_INITDB_SCRIPTS: /docker-entrypoint-initdb.d/init.js

  jenkins:
    image: tyriongump/jenkins:hermes
    restart: "no"
    ports:
      - ${HERMES_JENKINS_PORT:-8080}:8080
      - ${HERMES_JENKINS_JNLP_PORT:-50000}:50000










