name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GRADLE_VERSION: "8.1.1"
  JDK_VERSION: "17"

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out the current branch
      uses: actions/checkout@v3

    
    # secrets.APPLICATION_PROPERTIES is the content instead of the path to application.properties
    - name: Create application.properties
      run:
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > application.properties
        
    - name: Create container resources required by hermes-producer
      run: docker compose up -f docker/local/docker-compose.yaml -d --build
      
    - name: Build with Gradle
      run: docker run \
           --network host \ 
           --rm --mount type=bind,source="$(pwd)",target=/home/gradle/project \ 
           -w /home/gradle/project gradle:${{ env.GRADLE_VERSION }}-jdk${{ env.JDK_VERSION }}-jammy \
           bash -c "gradle -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xms256M -Xmx1g' \
                           -PhermesProducerAppProps=/home/gradle/project/application.properties \
                           -i clean -x test check build"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/TEST-*.xml'
        
    - name: Clean up Docker resources
      if: always()
      run: docker compose down
    
    - name: Remove Remove application.properties
      if: always()
      run:
        rm application.properties
      
  test-report:
    runs-on: ubuntu-22.04
    needs: build
    if: always()

    steps:
    - name: Check out the current branch
      uses: actions/checkout@v3

    - name: Download test results
      uses: actions/download-artifact@v3
      with:
        name: test-results

    - name: Display test results summary
      uses: dorny/test-reporter@v1.6.0
      with:
        name: Test Results
        path: '**/TEST-*.xml'
        reporter: java-junit

    
